### ISSUE TITLE
Does this package work along the sides of another database package?

### ISSUE THREAD

**Issue by JoseGeorges8** [zubairehman/Flogs#11]
I haven't tried the plugin yet, but I was wondering if there would be an issue with having already a local db in the app (currently using the [sqflite](https://pub.dev/packages/sqflite) package)

**Comment by zubairehman** [comment]
Hi, as FLogs has its own db so it won't disturb your app's db. It will work perfectly fine :)

**Comment by JoseGeorges8** [comment]
Just added the package to the existing sqflite project and there's really no issues
