### ISSUE TITLE
How to configure automate log deletion

### ISSUE THREAD

**Issue by ashanjayasundara** [zubairehman/Flogs#12]
I just install **f_logs: 1.2.0** version from dart packages and i couldn't find **deleteAllLogsByFilter** method so which release do i need to use

**Comment by slc1973** [comment]
Changes was merged to master but new release was never created. Release 1.2.0 is old one

**Comment by zubairehman** [comment]
New release will be pushed soon

**Comment by zubairehman** [comment]
> I just install **f_logs: 1.2.0** version from dart packages and i couldn't find **deleteAllLogsByFilter** method so which release do i need to use

version 1.2.1 has been upload, now you can access **deleteAllLogsByFilter** method :)

**Comment by slc1973** [comment]
This issue can be closed

**Comment by ashanjayasundara** [comment]
yes its available on 1.2.1 version
