### ISSUE TITLE
fieldOrderFormatCustom not honoured

### ISSUE THREAD

**Issue by ramtin-shams** [zubairehman/Flogs#13]
I have the following custom config in my code
 LogsConfig config = FLog.getDefaultConfigurations()
    ..isLogsEnabled = true
    ..timestampFormat = TimestampFormat.TIME_FORMAT_FULL_3
    ..fieldOrderFormatCustom = [
      FieldName.TIMESTAMP,
      FieldName.LOG_LEVEL,
      FieldName.CLASSNAME,
      FieldName.METHOD_NAME,
      FieldName.TEXT,
      FieldName.EXCEPTION,
      FieldName.STACKTRACE
    ]
    ..isDebuggable = true;
  FLog.applyConfigurations(config);

fieldOrderFormat is printed as default:
I/flutter ( 4209): {Assets} {loadFile} {Using the cached copy of assets/files/check.png.} {LogLevel.INFO} {2019-10-22 22:32:48}

**Comment by slc1973** [comment]
Hi,

you must enable custom format to use this:

``
    ..formatType = FormatType.FORMAT_CUSTOM
``

To set fieldOrderFormatCustom is not enough...

_FormatType.FORMAT_CURLY_ is default and must be overwritten

**Comment by ramtin-shams** [comment]
Thanks a lot for the response. That worked. 
Perhaps something for the author to include in the documentation.
