### ISSUE TITLE
Timestamp as DateTime when exporting log entries

### ISSUE THREAD

**Issue by Laban1** [zubairehman/Flogs#14]
Hello,

I am trying to use Flogs and was trying to export log entries and send them to a back-end server as JSON.  However, the timestamp fields in Flogs comes out as strings, e.g.:
"28 October 2019 01:44:28 PM"

This format cannot be parsed by DateTime, so no easy way to turn it into a DateTime field.  Storing a timestamp on the back-end server as a string in the above format is not very useful.  

Is there a way to get the the timestamp as a DateTime?

Thanks.

**Comment by zubairehman** [comment]
Hi,
You can easily convert the above timestamp in your desired format but have a look at this model in which you are getting timestamp in milliseconds as well. https://github.com/zubairehman/Flogs/blob/master/lib/model/flog/log.dart

Hope this helps

**Comment by Laban1** [comment]
Hi,

The milliseconds should do it!  I will give it a try.

Thanks.

Ps. I am new to Flutter / Dart; could you give an example of how to convert the above string to a DateTime (without the use of 3rd party date-time parsing packages)?
