### ISSUE TITLE
Question re. await for flogs calls

### ISSUE THREAD

**Issue by Laban1** [zubairehman/Flogs#15]
Since the Flog logging calls are async methods, do you recommend using await for the calls (to prevent possibly logging out-of-sequence), or is it ok to skip the await?

E.g. 

    await FLog.info(text: '1234');
    await FLog.info(text: '5678');

or is this ok:

    FLog.info(text: '1234');
    FLog.info(text: '5678'); // will this always be logged after 1234 above?

Thanks.

**Comment by zubairehman** [comment]
The below code will work

```
FLog.info(text: '5678');
```
Sequence will be garenteed as it will await while writing logs into DB

```
/// _writeLogs

///

/// This will write logs to local database

static _writeLogs(Log log) async {

//check to see if user provides a valid configuration and logs are enabled

//if not then don't do anything

if (_isLogsConfigValid()) {

// skip write logs when log level is to low or

// active log level is not in enabled log levels

if (LogLevel.values.indexOf(_config.activeLogLevel) <=

LogLevel.values.indexOf(log.logLevel) &&

_config.logLevelsEnabled.contains(_config.activeLogLevel)) {

await _flogDao.insert(log);

//check to see if logcat debugging is enabled

if (_config.isDebuggable) {

print(Formatter.format(log, _config));

}

}

} else {

throw new Exception(Constants.EXCEPTION_NOT_INIT);

}

}
```

**Comment by Laban1** [comment]
Great, thanks for the quick response!
