### ISSUE TITLE
example app doesn't run with new version of localization

### ISSUE THREAD

**Issue by alexaccaci** [zubairehman/Flogs#19]
Hi,
I'm getting this error when trying to run the example app after adding flutter_localizations in pubspec.yaml:

Because no versions of f_logs match >1.2.1 <2.0.0 and f_logs 1.2.1 depends on intl ^0.15.8, f_logs ^1.2.1 requires intl ^0.15.8.

And because every version of flutter_localizations from sdk depends on intl 0.16.0, f_logs ^1.2.1 is incompatible with flutter_localizations from sdk.

So, because flutter_log depends on both flutter_localizations any from sdk and f_logs ^1.2.1, version solving failed.
pub get failed (1; So, because flutter_log depends on both flutter_localizations any from sdk and f_logs ^1.2.1, version solving failed.)

**Comment by parkskier426** [comment]
I've also run into this issue. Please update flogs to use 0.16.x!

**Comment by zubairehman** [comment]
please update to version v 1.2.2, hope this will fix your issue

**Comment by alexaccaci** [comment]
I have the issue using the version v1.2.2
Best Regards
Alex


Il giorno gio 13 feb 2020 alle ore 19:24 Zubair Rehman <
notifications@github.com> ha scritto:
