### ISSUE TITLE
f_logs >=1.2.2 is forbidden.

### ISSUE THREAD

**Issue by Ajit121** [zubairehman/Flogs#26]
I've included permission_handler: ^5.0.0+hotfix.3 in my project and now i'm not able to inclue f_logs
Because f_logs >=1.2.2 depends on permission_handler ^4.0.0 and app depends on permission_handler ^5.0.0+hotfix.3, f_logs >=1.2.2 is forbidden.

**Comment by olo95** [comment]
https://github.com/zubairehman/Flogs/pull/27 this should resolve our problem

**Comment by maerlynflagg** [comment]
same. currently i using my fork of this repo with updated package. hope the original will updated soon.


> I've included permission_handler: ^5.0.0+hotfix.3 in my project and now i'm not able to inclue f_logs
> Because f_logs >=1.2.2 depends on permission_handler ^4.0.0 and app depends on permission_handler ^5.0.0+hotfix.3, f_logs >=1.2.2 is forbidden.
