### ISSUE TITLE
Dependency on permission_handler

### ISSUE THREAD

**Issue by jaypatel04** [zubairehman/Flogs#29]
Error: Because f_logs >=1.2.2 depends on permission_handler ^4.0.0 and <MyApp> depends on permission_handler ^5.0.0+hotfix.6, f_logs >=1.2.2 is forbidden.

I would like to use permission_handler for other services, but not able to use it as log uses older version.

My pubspec.xml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: ^1.3.0+1
  path_provider: ^1.6.7
  permission_handler: ^5.0.0+hotfix.6
  contacts_service: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.3
  f_logs: 1.3.0-alpha-01
  mockito: ^4.1.1

**Comment by iKrupp** [comment]
Hi! It can help you:

dependency_overrides:
  permission_handler: 5.0.0+hotfix.5

**Comment by zubairehman** [comment]
The issue has been fixed, please use version: 1.3.0-alpha-02.

**Comment by jaypatel04** [comment]
> Hi! It can help you:
> 
> dependency_overrides:
> permission_handler: 5.0.0+hotfix.5

Hey thanks, this worked

**Comment by jaypatel04** [comment]
Both solutions 
(1) dependency_overrides:
permission_handler: 5.0.0+hotfix.5
(2) Using version 1.3.0-alpha-02
worked.
Thanks a lot for quick replies.
