### ISSUE TITLE
Concerning iOS permissions

### ISSUE THREAD

**Issue by RemeJuan** [zubairehman/Flogs#36]
I have installed this, and not even set it up yet, and Apple rejected it from TestFlight for a series of concerning permissions that are not even included as part of the documentation.

Why would the logging app need access too:
```
NSContactsUsageDescription
NSCalendarsUsageDescription
NSAppleMusicUsageDescription
NSMotionUsageDescription
NSSpeechRecognitionUsageDescription
NSLocationAlwaysUsageDescription
NSLocationWhenInUseUsageDescription
```

That is a long list of very invasive and seemingly unnecessary permissions that are required in order to even get the app accepted by TestFlight, Music, Real-time location.

**Comment by ristiisa** [comment]
@zubairehman
@olo95 
@bierbaumtim 
@rodydavis

**Comment by bierbaumtim** [comment]
I use this package in production and does not have such problems. But for me it looks similar to Problem that I had with permissions_handler. 
Are you sure that this package itself causes the problem?
Are you using permissions_handler package or something similar?

**Comment by RemeJuan** [comment]
> I use this package in production and does not have such problems. But for me it looks similar to Problem that I had with permissions_handler. 
> Are you sure that this package itself causes the problem?
> Are you using permissions_handler package or something similar?

Never even heard of that package, and quite certain, I wanted to debug something, installed this, ran a release and got told to fly a kite by Apple. Added the permissions to plist, Apple was happy and when I was done I killed the branch, deployed off the base again and all was good.

Few weeks later tried it again for another issue and exact same thing happened, at which point I created this issue.

No way it happens twice when the only difference between before and after is this package. The only permission the app needs extra is gallery for image uploading. We access nothing else on a device.

**Comment by ristiisa** [comment]
Today I submitted a build to TF that succeeded, then I added this library and submitted another build that failed

**Comment by bierbaumtim** [comment]
After some research I found the issue. In Version 1.2.2 the permission_handler plugin is included in this package but is only used in the example app. In production I use a fork without the permission_handler plugin therefore I never had such issues. 

As a solution you can use version 1.3.0-alpha-02, which contains most of the changes I made in my fork.

**Comment by ristiisa** [comment]
For me 1.3.0-alpha-02 has been working (in a sense of releasing) in a TF and production
