### ISSUE TITLE
LogLevel is not respected.

### ISSUE THREAD

**Issue by janniklind** [zubairehman/Flogs#4]
I haven't actually tested this logging framework yet, I just had a quick look at the code before I would start to use the package. It seems in this line, that the LogLevel is not respected.

https://github.com/zubairehman/Flogs/blob/master/lib/model/flog/flog.dart#L324

Please correct me, if I am wrong :)

**Comment by zubairehman** [comment]
yes, you are right. It should be:

```
Log log = Log(
        className: className,
        methodName: methodName,
        text: text,
        logLevel: type, // new change
        dataLogType: dataLogType,
        exception: exception.toString(),
        timestamp: DateTimeUtils.getCurrentTimestamp(_config),
        timeInMillis: DateTimeUtils.getCurrentTimeInMillis(),
      );
```

Thanks for correction :)

**Comment by janniklind** [comment]
You might also have a problem in the following line, in case Exception is null:
https://github.com/zubairehman/Flogs/blob/master/lib/model/flog/flog.dart#L326
