### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by bigbang489** [zubairehman/Flogs#43]
Could you migrate your package to Null-safety?

**Comment by rgb1380** [comment]
Please check the compatibility of the package with Fluter 2.0. In particular, there seems to be an issue with use of intl 0.16.0 package which needs to be upgraded to version 0.17.0

This is a great plugin and will be great if the author could continue maintaining it.

**Comment by zubairehman** [comment]
Hi @all,

Flogs now supports null-safety, please use v2.0.0 that is available on pub.dev.

Thanks.
