### ISSUE TITLE
Flutter Version 2.0

### ISSUE THREAD

**Issue by josediegopassos** [zubairehman/Flogs#45]
I updated the flutter and the f_logs stopped working because of the dependencies

**Comment by lutang123** [comment]
same here, not sure if this package will update, it doesn't seem to be active.

**Comment by josediegopassos** [comment]
> mesmo aqui, não tenho certeza se este pacote será atualizado, ele não parece estar ativo.

This is very bad.
I really enjoyed using this lib.

**Comment by maerlynflagg** [comment]
i upgraded the flutter 2 to and it stopped working.

**Comment by NetiSade** [comment]
Same here

**Comment by zubairehman** [comment]
will publish a new version soon, stay tuned

**Comment by zubairehman** [comment]
Hi everyone,

2.0.0-alpha-01 is public now, please try that out and let me know if there are any issues. 

Thanks.
