### ISSUE TITLE
RangeError (RangeError (index): Invalid value: Only valid value is 0: 1)

### ISSUE THREAD

**Issue by ristiisa** [zubairehman/Flogs#48]
_logThis https://github.com/zubairehman/Flogs/blob/master/lib/model/flog/flog.dart#L397 should check if the `Trace.current().frames[2].member` has enough elements after splitting the name.

**Comment by zubairehman** [comment]
Hi @ristiisa,
Could you please share the complete stack trace and your usecase?

**Comment by y1337x** [comment]
![stacktrace_error](https://user-images.githubusercontent.com/5759667/121316552-bd22df80-c909-11eb-8876-a19e83e0e07d.png)
`Trace.current().frames[2].member!` returns FLog.info but when `.split` is called, its content is main. I think you have to call `StackTrace.current` once befor entering the if statements.
