### ISSUE TITLE
FLog.clearLogs() does not work properly

### ISSUE THREAD

**Issue by olga0** [zubairehman/Flogs#5]
FLog.clearLogs() does not delete data from database. When I call clearLogs(), close my app, open it again and call FLog.printLogs() I see all my logs again.

**Comment by olga0** [comment]
Clearing logs still does not work. The same bug.

**Comment by zubairehman** [comment]
make sure you are using version:   `f_logs: ^1.2.0`

**Comment by olga0** [comment]
Yes, I used version 1.2.0
