### ISSUE TITLE
Unhandled Exception: type 'Future<List<RecordSnapshot<int, Map<String, Object?>>>>' is not a subtype of type 'FutureOr<List<RecordSnapshot<int, Map<String, Object>>>>' in type cast

### ISSUE THREAD

**Issue by FirdousNath** [zubairehman/Flogs#56]
When I run `FLog.exportLogs` method it gives following error.

` File file = await FLog.exportLogs();`

```
Unhandled Exception: type 'Future<List<RecordSnapshot<int, Map<String, Object?>>>>' is not a subtype of type 'FutureOr<List<RecordSnapshot<int, Map<String, Object>>>>' in type cast

#0      FlogDao.getAllLogs
package:f_logs/…/local/flog_dao.dart:100
<asynchronous suspension>
#1      FLog._getAllLogs
package:f_logs/…/flog/flog.dart:433
<asynchronous suspension>
#2      FLog.exportLogs
package:f_logs/…/flog/flog.dart:262
<asynchronous suspension>
```

_I am using latest null safety version 2.0.0_

dart compiler points to following in **flog_dao.dart** file. 
`Future<List<Log>> getAllLogs() async {
    final recordSnapshots = await (_flogsStore.find(
      await _db,
    ) as FutureOr<List<RecordSnapshot<int, Map<String, Object>>>>);
`

**Comment by Vasilisk7** [comment]
I have the same problem.

**Comment by rikinmprajapati** [comment]
Follow the below solution for now
https://github.com/zubairehman/Flogs/issues/51#issuecomment-847681893

**Comment by zubairehman** [comment]
Hi,
The latest version of flogs (v2.0.1) has been released, please try that out and let me know if the issue persists.
Thanks
