### ISSUE TITLE
Can not open the flog.db

### ISSUE THREAD

**Issue by zKidor** [zubairehman/Flogs#64]
Hi,
 I run the demo  on github , on android 9 ,  and export the flog.db . But I can not open it. I have tried different kinds of sqlite client . but it seems not work .
![image](https://user-images.githubusercontent.com/17610041/126267597-3ab33a36-2d0c-4067-a20c-c20bc3f78e8e.png)

![image](https://user-images.githubusercontent.com/17610041/126267753-56cca416-bccd-4476-9cd1-056c4fc45cdc.png)

how can I fix this? 
 Thank you

**Comment by ristiisa** [comment]
because it is not sqlite database. https://github.com/tekartik/sembast.dart
