### ISSUE TITLE
No releases published

### ISSUE THREAD

**Issue by slc1973** [zubairehman/Flogs#71]
Hi @zubairehman!

I noticed Flogs code has no releases here on github.com and git tags are not used to keep track of specific points in a Git repository’s history.

For check how it works i added in my feature branch git tag "v2.0.0-alpha-01" and i created a (pre-)release based on this tag.
After creation release looks like example here: https://github.com/slc1973/Flogs/releases

How do you like this idea?

Further develop branch of this project is 43 commits behind master. I think it's better when contributors create pull requests to develop branch and not to master branch (how I did it too :( ). But pre-condition for this is to keep develop branch up to date. I hope I am not saying anything wrong ;) OR delete develop branch if it's not used...

Have a great time!

**Comment by AlexanderWesten** [comment]
Hi @zubairehman,

thanks for the great repo! I saw that you made a few changes some days ago, which are much appreciated. 
Would it be possible to publish your latest changes as a regular release?

Thanks in advance!

**Comment by zubairehman** [comment]
@AlexanderWesten we have been planning to release frequently :)

**Comment by zubairehman** [comment]
the latest version of flogs (f_logs: ^2.0.1) has been released, please try that out and thanks you for you support :)
