### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by mjablecnik** [zubairehman/Flogs#73]
@zubairehman 
Is this project dead? Because I see a lot of PR or Issues which is nobody resolving for last half year..

**Comment by mjablecnik** [comment]
So original author of this package doesn't respond here or in email so I created own fork (where I made some improvements and changes) which I plan maintain. If you are interested about my project so you can find it here: https://pub.dev/packages/my_logger

**Comment by luvishq** [comment]
@mjablecnik : Are the issues mentioned in this repo addressed in your version?

**Comment by zubairehman** [comment]
no its not
