### ISSUE TITLE
Import only one file instead of all the package files

### ISSUE THREAD

**Issue by rockingdice** [zubairehman/Flogs#8]
Thanks for the package. I'm just starting to use it, and what makes me confused is the import part from the readme.

How would I know which dart file should I import if I just want to log?

I think only importing one file is a better way and less difficult to use this package.

**Comment by slc1973** [comment]
Check it if this looks similar like what you want: https://github.com/zubairehman/Flogs/pull/9

Just a suggestion

**Comment by rockingdice** [comment]
That's what I need, thank you.
